spring:
  application:
    name: product-service
  data:
    mongodb:
      url: mongodb://localhost:27017/productService
eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka